spring:
  config:
    activate:
      on-profile: standalone

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://${POSTGRES_CONTAINER_NAME}:5432/${POSTGRES_DB}?reWriteBatchedInserts=true
    driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_1}:8092,${KAFKA_2}:8094,${KAFKA_3}:8096
