version: "2.39"

services:
  application:
    build:
      context: ../
      dockerfile: ./docker/app.dockerfile
      args:
        APP_NAME: ${APP_NAME}
        APP_VERSION: ${APP_VERSION}
    container_name: 2track_app
    restart: unless-stopped
    ports:
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
      liquibase:
        condition: service_completed_successfully
    env_file:
      - .env
    volumes:
      - ../src/main/resources/secrets:/secrets
    networks:
      - backend