version: "3.9"

name: docker_ttrack
services:

  database:
    image: postgres:16
    container_name: postgresql_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - postgresql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 3s
      timeout: 6s
    networks:
      - backend

  liquibase:
    image: liquibase/liquibase:4.25
    container_name: liquibase_db
    restart: no
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    command:
      - --changelog-file=db.changelog.yml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://${POSTGRES_CONTAINER_NAME}:5432/${POSTGRES_DB}
      - --username=${POSTGRES_USER}
      - --password=${POSTGRES_PASSWORD}
      - update
    volumes:
      - ../migrations/db/changelog:/liquibase/changelog
    networks:
      - backend

volumes:
  postgresql: {}

networks:
  backend:
    driver: bridge